### PR TITLE
Remove includes config from globals

### LINKED ISSUE #98: globals config not working with dependencies
I faced this issue while using `@radix-ui/<some-component>` which the `wp_scripts()` plugin.

The generated output did not account for the dependency's dependency (radix-ui depending on react).

image

The specific error shown in console says something like import url of react is invalid and if you go check the generated js (without minify) you can see that it is including some `import * as React$1 from "react"` which after some debugging I found out where only appearing while including the code that uses radix-ui.

image

After some trial and error I found out that there are some specific includes set to the `rollup-plugin-external-globals` config inside `wp-scripts.js` and after checking the documentation there seems to be no need for this, commenting it out did fix the issue and the globals were correctly defined. 

This is useful if you are willing to integrate shadcn components in your plugin. Can't tell if also happens with other dependencies that also depend on react but might be the case.

image

So far that change has not caused any side effect on my project but surely you had a reason for that and maybe a fix can be figured out from there.

### PR DESCRIPTION
**Pull request by Bernix01**
This changes fixes #98

### CODE REVIEW

File: src/exports/plugins/wp-scripts.js [hunk 1]
```diff
@@ -57,8 +57,6 @@ export async function wp_scripts( options = {} ) {
 		externals( {
 			externals: scripts,
 		} ),
-		globals( scripts, {
-			include: [ '**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx' ],
-		} ),
+		globals(scripts),
```
Comment (kucrut) [inline src/exports/plugins/wp-scripts.js:60]:
```suggestion
		globals( scripts ),
```

**Review by kucrut — CHANGES_REQUESTED** [review]
Thank you for the PR @Bernix01. Just a minor coding style issue need to be fixed and I'll merge this right away as I just encountered this bug myself :wink:

**Review by kucrut — APPROVED** [review]
